/* generated by bdf-convert.rb */

#ifndef FONT_BDF_CONV_H
#define FONT_BDF_CONV_H

#ifdef __cplusplus
#include <cstdint>
#else
#include <stdint.h>
#endif

typedef struct {
    uint8_t encoding;
    uint8_t bbx_x;
    uint8_t bbx_y;
    int8_t bbx_offx;
    int8_t bbx_offy;
    uint8_t dwidth;
    uint8_t *bmp;
} Glyph;

typedef struct {
    uint8_t fbbx_x;
    uint8_t fbbx_y;
    int8_t fbbx_offx;
    int8_t fbbx_offy;
    uint32_t num_chars;
    Glyph** glyph_table;
} Font;

#endif // FONT_BDF_CONV_H
